import { Inter } from "next/font/google";
import "./globals.css";
import PageHeader from "@/components/PageHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Book Health Packages",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageHeader />

        <main>{children}</main>
      </body>
    </html>
  );
}
